Add validations and unit tests
Tamunokuro/RoR_Blog pull request #3
Opened 2023-03-10 00:58 UTC by Tamunokuro

- [x] Add the following validations:
  - [x] For the User model:
    - Name must not be blank.
    - PostsCounter must be an integer greater than or equal to zero.
  - [x] For the Post model:
    - Title must not be blank.
    - Title must not exceed 250 characters.
    - CommentsCounter must be an integer greater than or equal to zero.
    - LikesCounter must be an integer greater than or equal to zero.
- [x] Add unit specs for all of your models' methods and validations.

2023-03-10 01:24 UTC, andersonlebon requested changes
## Hi @Tamunokuro 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 01:24 UTC, andersonlebon commented on spec/models/user/user_spec.rb
> +end
- [ ] Kindly note that all custom methods on models should be tested also, Kindly make sure the `most_recent_posts` is tested here

2023-03-10 01:24 UTC, andersonlebon commented on spec/models/post/post_spec.rb
> +end
- [ ] Kindly note that all custom methods in models should be tested also, Kindly make sure the `recent_comments` and `posts_counter` is tested here.

2023-03-10 01:24 UTC, andersonlebon commented on spec/models/comment/comment_spec.rb
> +end
- [ ] Kindly note that all custom methods in models should be tested also, Kindly make sure the `comments_counter` and `decrement_comments_counter` are tested here.

2023-03-10 01:24 UTC, andersonlebon commented on spec/models/post/post_spec.rb
> +end
- [ ] Kindly note that all custom methods in models should be tested also, Kindly make sure the `recent_comments` and `posts_counter` are tested here.

2023-03-10 01:24 UTC, andersonlebon commented on spec/models/like/like_spec.rb
> +end
- [ ] Kindly note that all custom methods in models should be tested also, Kindly make sure the `likes_counter` is tested here.

2023-03-11 01:06 UTC, AshakaE approved these changes
Hi @Tamunokuro , 

### Highlights ✨ 

- Thanks for making the requested changes 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-11 01:20 UTC, merged